# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'microblaze_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'microblaze_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/manuel/Desktop/Display/Display.srcs/sources_1/bd/microblaze/ip/microblaze_rst_clk_wiz_0_100M_0/microblaze_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
